version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
    labels:
      plugsy.name: "Minecraft"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/simple-icons/Minecraft"
      plugsy.link: "http://${LAN_IP}:25565"
