version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
    volumes:
      - ./data:/config
    ports:
      - 8880:8080
      - 8881:8081
    restart: unless-stopped
    labels:
      plugsy.name: "Calibre"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/fa-solid/Book"
      plugsy.link: "http://${LAN_IP}:8880"
