version: "2.1"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      - 82:80
      - 441:443
    restart: unless-stopped
    labels:
      plugsy.name: "snapdrop"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/boxicons-regular/CloudUpload"
      plugsy.link: "http://${LAN_IP}:82"
