version: '2.1'
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - ./data:/app/data
    ports:
      - 5005:5005
    environment:
      - PASSWORD=password
    restart: unless-stopped
    labels:
      plugsy.name: "Flame"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/fa-solid/Flame"
      plugsy.link: "http://${LAN_IP}:5005"
