version: "3.0"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "${LAN_IP}:8410:80"
    command: "--memcached=memcached:11211 --port 80"