version: '3.3'
services:
    speedtest:
        container_name: speedtest-tracker
        image: henrywhitaker3/speedtest-tracker:latest
        ports:
            - 8765:80
        volumes:
            - /path/to/data:/config
        environment:
            - OOKLA_EULA_GDPR=true
            - AUTH=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

# The default login is
# Email address: admin@admin.com
# Password: password
