version: '3.9'

services:
    mixpost:
        image: "inovector/mixpost:v1.1.1"
        environment:
            APP_NAME: Mixpost
            APP_URL: ${LAN_IP}
            DB_DATABASE: db1
            DB_USERNAME: dbuser
            DB_PASSWORD: ${GEN_PASS}
            REDIS_PASSWORD: ${GEN_PASS2}
        ports:
            - 8736:80
        volumes:
            - ./mixpost-storage:/var/www/html/storage/app
            - ./mixpost-logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis
    mysql:
        image: "mysql/mysql-server:8.0.32"
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: db1
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: ${GEN_PASS}
        volumes:
            - 'mixpost-mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p ${MIXPOST_DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: "${REDIS_RELEASE_NAME}:${REDIS_RELEASE_VERSION}"
        command: redis-server --appendonly yes --replica-read-only no --requirepass "${GEN_PASS2}"
        ports:
            - '6379:6379'
        volumes:
            - 'mixpost-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
volumes:
    mixpost-mysql:
        driver: local
    mixpost-redis:
        driver: local
    mixpost-storage:
        driver: local
    mixpost-logs:
        driver: local
