version: "2.1"
services:
  nano-wallet:
    image: lscr.io/linuxserver/nano-wallet:latest
    container_name: nano-wallet
    ports:
      - 85:80
    restart: unless-stopped
    labels:
      plugsy.name: "nano-wallet"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/crypto/Bitcoin"
      plugsy.link: "http://${LAN_IP}:85"
