version: '3.3'
services:
    run:
        volumes:
            - '`pwd`/data:/app/data'
        ports:
            - '8482:8080'
            - '1935:1935'
        image: run
# Fw internal/external TorGuard wireguard port tcp 1935
