version: '3'

volumes:
  webtop_config:

services:
  webtop:
    restart: unless-stopped
    image: lscr.io/linuxserver/webtop
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    labels:
      plugsy.name: "WebTop"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/icomoon/Windows"
      plugsy.link: "http://${LAN_IP}:3000"
