version: '3'

volumes:
  filebrowser_config:
  filebrowser_data:

services:
  filebrowser:
    restart: unless-stopped
    image: hurlenko/filebrowser
    volumes:
      - ./config:/config
      - /opt/docker2/compose:/data
    environment:
      - FB_BASEURL=/filebrowser
    ports:
      - 8984:8080
    labels:
      plugsy.name: "Filebrowser"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/fa-solid/FolderOpen"
      plugsy.link: "http://${LAN_IP}:8984"
