version: "2.1"
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      - 3938:3000
    restart: unless-stopped
    labels:
      plugsy.name: "libreoffice"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/simple-icons/Libreoffice"
      plugsy.link: "http://${LAN_IP}:3938"
