version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    labels:
      plugsy.name: "VScode"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/simple-icons/Visualstudiocode"
      plugsy.link: "http://${LAN_IP}:8443"
