version: '3.7'

services:
  searxng:
    image: searxng/searxng:latest
    restart: always
    ports:
      - ${LAN_IP}:8125:8080
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - IMAGE_PROXY=true
      - BASE_URL=http://${LAN_IP}
      - NAME=SearXNG
      - CONTACT=contact@searxng.org
      - ISSUE_URL=https://github.com/searxng/searxng/issues
      - GIT_URL=https://github.com/searxng/searxng
      - GIT_BRANCH=main
    labels:
      plugsy.name: "SearXNG"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/boxicons-regular/Search"
      plugsy.link: "http://${LAN_IP}:8125"
