version: "2.1"
services:
  rdesktop:
    image: lscr.io/linuxserver/rdesktop:ubuntu-kde
 #  image: lscr.io/linuxserver/rdesktop:latest
 #  image: lscr.io/linuxserver/rdesktop:fedora-xfce
 #  image: lscr.io/linuxserver/rdesktop:arch-xfce
 #  image: lscr.io/linuxserver/rdesktop:alpine-kde
 #  image: lscr.io/linuxserver/rdesktop:alpine-mate
 #  image: lscr.io/linuxserver/rdesktop:fedora-kde
 #  image: lscr.io/linuxserver/rdesktop:ubuntu-mate
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
 #     - FILE__PASSWORD=/run/secrets/mysecretpassword
    volumes:
      - ./data:/config #optional
    ports:
      - 3389:3389
    shm_size: "1gb" #optional
    restart: unless-stopped
