version: '3'

volumes:
  mstream_config:
  msteam_music:
  
services:
  mstream:
    restart: unless-stopped
    image: lscr.io/linuxserver/mstream
    volumes:
      - ./config:/config
      - ./music:/music
    ports:
      - 3300:3000
    labels:
      plugsy.name: "mstream"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/boxicons-solid/Music"
      plugsy.link: "http://${LAN_IP}:3300"
