version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./appdata/config:/config
      - ./music:/music #optional
      - ./downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      plugsy.name: "Lidarr"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/simple-icons/Lidarr"
      plugsy.link: "http://${LAN_IP}:8686"
