version: '3.3'
services:
    libreddit:
        container_name: libreddit
        ports:
            - '5741:8080'
        restart: always
        image: spikecodes/libreddit
    labels:
      plugsy.name: "libreddit"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/boxicons-logos/RedditSquare"
      plugsy.link: "http://${LAN_IP}:5741"    
