version: "2.1"
services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest
    container_name: audacity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      - 3200:3000
    restart: unless-stopped
    labels:
      plugsy.name: "Audacity"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/fa-brands/audible"
      plugsy.link: "http://${LAN_IP}:3200"
