version: '3'

volumes:
  homeassistant_config:

services:
  homeassistant:
    restart: unless-stopped
    network_mode: "host" 
    image: lscr.io/linuxserver/homeassistant
    volumes:
      - ./data:/config
    ports:
      - 8123:8123
    labels:
      plugsy.name: "Homeassistant"
      plugsy.category: "Home"
      plugsy.icon: "@styled-icons/fa-solid/Home"
      plugsy.link: "http://${LAN_IP}:8123"
